# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PRISONER
email: luke.hutton@open.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  PRISONER is a framework for running ethical and privacy-preserving
  social network experiments.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://uoscompsci.github.io/PRISONER/" # the base hostname & protocol for your site
twitter_username: EthicsPRISONER
github_username:  barneyboo

# Build settings
markdown: kramdown
